/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

/**
 *
 * @author ROOT
 */
public class PanelCreacionExamen extends javax.swing.JFrame {

    /**
     * Creates new form PanelCreacionExamen
     */
    public PanelCreacionExamen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTextoPregunta = new javax.swing.JLabel();
        lblSegundaRespuesta = new javax.swing.JLabel();
        lblPrimeraRespuesta = new javax.swing.JLabel();
        lblTerceraRespuesta = new javax.swing.JLabel();
        lblCuartaRespuesta = new javax.swing.JLabel();
        lblRespuestaCorrecta = new javax.swing.JLabel();
        txtTextoPregunta = new javax.swing.JTextField();
        txtTextoPrimeraRespuesta = new javax.swing.JTextField();
        txtTextoSegundaRespuesta = new javax.swing.JTextField();
        txtTextoTerceraRespuesta = new javax.swing.JTextField();
        txtTextoCuartaRespuesta = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        buttRegresar = new javax.swing.JButton();
        buttSiguientePregunta = new javax.swing.JButton();
        buttFinalizarCreacion = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel1.setToolTipText("");

        lblTextoPregunta.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblTextoPregunta.setText("Texto pregunta:");

        lblSegundaRespuesta.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblSegundaRespuesta.setText("Segunda Respuesta");

        lblPrimeraRespuesta.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblPrimeraRespuesta.setText("Primera Respuesta:");

        lblTerceraRespuesta.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblTerceraRespuesta.setText("Tercera Respuesta");

        lblCuartaRespuesta.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblCuartaRespuesta.setText("Cuarta Respuesta");

        lblRespuestaCorrecta.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblRespuestaCorrecta.setText("Respuesta correcta");

        txtTextoPregunta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTextoPreguntaActionPerformed(evt);
            }
        });

        txtTextoTerceraRespuesta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTextoTerceraRespuestaActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblTextoPregunta)
                        .addGap(18, 18, 18)
                        .addComponent(txtTextoPregunta, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblPrimeraRespuesta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTextoPrimeraRespuesta))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblTerceraRespuesta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtTextoTerceraRespuesta))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblCuartaRespuesta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtTextoCuartaRespuesta))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblRespuestaCorrecta)
                        .addGap(28, 28, 28)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblSegundaRespuesta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTextoSegundaRespuesta)))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTextoPregunta)
                    .addComponent(txtTextoPregunta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPrimeraRespuesta)
                    .addComponent(txtTextoPrimeraRespuesta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSegundaRespuesta, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTextoSegundaRespuesta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTerceraRespuesta)
                    .addComponent(txtTextoTerceraRespuesta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCuartaRespuesta)
                    .addComponent(txtTextoCuartaRespuesta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRespuestaCorrecta)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 23, Short.MAX_VALUE))
        );

        buttRegresar.setText("Regresar");

        buttSiguientePregunta.setText("Siguiente");

        buttFinalizarCreacion.setText("Finalizar");

        jLabel1.setFont(new java.awt.Font("Noto Sans", 0, 18)); // NOI18N
        jLabel1.setText("Creacion de Examen");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(buttRegresar)
                        .addGap(43, 43, 43)
                        .addComponent(buttSiguientePregunta)
                        .addGap(49, 49, 49)
                        .addComponent(buttFinalizarCreacion)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
            .addGroup(layout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(21, 21, 21)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttRegresar)
                    .addComponent(buttSiguientePregunta)
                    .addComponent(buttFinalizarCreacion))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void txtTextoPreguntaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTextoPreguntaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTextoPreguntaActionPerformed

    private void txtTextoTerceraRespuestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTextoTerceraRespuestaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTextoTerceraRespuestaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PanelCreacionExamen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PanelCreacionExamen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PanelCreacionExamen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PanelCreacionExamen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PanelCreacionExamen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttFinalizarCreacion;
    private javax.swing.JButton buttRegresar;
    private javax.swing.JButton buttSiguientePregunta;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCuartaRespuesta;
    private javax.swing.JLabel lblPrimeraRespuesta;
    private javax.swing.JLabel lblRespuestaCorrecta;
    private javax.swing.JLabel lblSegundaRespuesta;
    private javax.swing.JLabel lblTerceraRespuesta;
    private javax.swing.JLabel lblTextoPregunta;
    private javax.swing.JTextField txtTextoCuartaRespuesta;
    private javax.swing.JTextField txtTextoPregunta;
    private javax.swing.JTextField txtTextoPrimeraRespuesta;
    private javax.swing.JTextField txtTextoSegundaRespuesta;
    private javax.swing.JTextField txtTextoTerceraRespuesta;
    // End of variables declaration//GEN-END:variables
}
